### ISSUE TITLE
I am getting this error - Starting to generate trx XML output. System.BadImageFormatException: Could not load file or assembly

### ISSUE THREAD

**Issue by Akankshaa-Agrawal** [markvincze/MsTestTrxLogger#1]
Starting to generate trx XML output. System.BadImageFormatException: Could not load file or assembly

I have copied given binaries to my visual studio extension and when I am trying to execute the Tests it;s giving above error : Could it be because X64 platform ?

"C:\Program Files (x86)\Microsoft Visual Studio 12.0"\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe C:\GitAutomationRepo\FunctionalSpecs\seSpecs\bin\Debug\seSpecs.dll  /UseVsixExtensions:true /testcasefilter:"TestCategory=RunTest" /Logger:MsTestTrxLogger  /Platform:x64 /Settings:C:\GitAutomationRepo\FunctionalSpecs\seSpecs\output.runsettings 

![image](https://cloud.githubusercontent.com/assets/15230342/22771498/0708f138-eebd-11e6-96f9-9da4d99f4e63.png)

Thanks in advance

**Comment by markvincze** [comment]
Hi @akankshaaSaba,

I haven't encountered this exception before, so from the top of my head I don't know what can cause this.
If you remove the binaries and try again, do you get the same exception, or something different?
Can you also try without the `/Platform:x64` flag (I don't think I have used that before) or is that necessary for your tests to work?

**Comment by Akankshaa-Agrawal** [comment]
If I try with /Logger:trx it perfectly works fine.Somehow its not loading
the .dll not sure why.

/Platform:x64 is needed for my tests.

**Comment by Akankshaa-Agrawal** [comment]
It worked for me when i changed my project setting to get build on ANy CPU instead on X64 and my tests I am executing on Platform:X64

Thanks for the Tool..

**Comment by markvincze** [comment]
Hi @akankshaaSaba,

Sorry, I didn't have much time last week to investigate the issue.  
I'm glad you managed to find a fix, and thanks for sharing the solution!

Cheers,
Mark
