### ISSUE TITLE
Total number of tests executed and number of tests displayed in trx report are different . It seems after failure of one test case it does n't count further cases. Also the trx generated doesn't gets opened in visual studio

### ISSUE THREAD

**Issue by Akankshaa-Agrawal** [markvincze/MsTestTrxLogger#2]
Attached the generated trx  and error screenshot after opening the trx in Visual Studio
Total Number of cases executed by vstest.console.exe
![image](https://cloud.githubusercontent.com/assets/15230342/22872401/f8fb9422-f1de-11e6-86df-0c3ce28745bc.png)
WHen trx opnened in Visual studio
![image](https://cloud.githubusercontent.com/assets/15230342/22872364/b5e50182-f1de-11e6-837b-ad7079a922ce.png)

Trx file which got generated.
[uitestresults(1).zip](https://github.com/markvincze/MsTestTrxLogger/files/770198/uitestresults.1.zip)

Specflow file generate and displayed the incorrect number of tests

**Comment by markvincze** [comment]
Hey @akankshaaSaba,

Sorry, somehow I missed this issue. I'll try to take a look this weekend.
Is your codebase by any chance open source, so I can take a look at the tests?

**Comment by LediLederer** [comment]
Thank you for providing the  MsTestTrxLogger code which helped me a lot to understand how VsTest is working!

The reason for VS not being able to open the trx file is a violation against the TRX XML schema (typo in "queueing" and wrong structure in TestCategory) in the file that is generated. i have a fix at hand, including update to VS 2015 regarding current nuget dependencies.
Wanna have it?

**Comment by markvincze** [comment]
Fixed in #9
