### ISSUE TITLE
using MsTestTrxLogger' VS2015 with vstest.console.exe results with Could not find a test logger with URI or FriendlyName

### ISSUE THREAD

**Issue by EyalShlomi** [markvincze/MsTestTrxLogger#3]
Hi,

I'm using Visual studio 2015 Ent.
I'm trying to use 'MsTestTrxLogger' with vstest.console.exe and I get the following error:
Error: Could not find a test logger with URI or FriendlyName 'MsTestTrxLogger'.
my usage syntax is:
vstest.console.exe   myTestDll.dll    /Tests:test0001    /logger:MsTestTrxLogger

**Comment by markvincze** [comment]
Hi @EyalShlomi,

Did you copy the binaries to `C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions`?  
Depending on your VS version and your architecture, the folder might be slightly different, I remember that it can be a bit confusing to figure out which is the right one, this was the folder that worked for me. If you're using VS 2015, you might need to copy it to the folder under the version number `14.0`.

**Comment by EyalShlomi** [comment]
Hi,

Yes I did.
only after restart of PC the error stopped.
Testing it right now.
All is OK. Its working. 
Great app btw.

**Comment by markvincze** [comment]
Interesting, I didn't remember it needed a restart. Anyway, I'm glad it's solved!
