### ISSUE TITLE
mstest.exe is now considered deprecated.

### ISSUE THREAD

**Issue by aligneddev** [markvincze/MsTestTrxLogger#4]
I've been wondering what Microsoft's recommendations are for mstest vs vstest and testsettings vs runsettings.

Do you have a reference for your Readme's "Later that was replaced by vstest.console.exe, and mstest.exe is now considered deprecated." statement?

Do you know how Mstest v2 plays into all of this?
https://blogs.msdn.microsoft.com/devops/2017/02/25/mstest-v2-now-and-ahead/

I'm curious. 

Thanks,
Kevin

**Comment by markvincze** [comment]
Hi @aligneddev,

No, I don't remember where I read that, but I investigated vstest and mstest at the time a lot, I *think* I read that somewhere in the docs.

I wasn't even aware of MsTest v2 being released, and I don't know what's Microsoft's recommendation.

**Comment by aligneddev** [comment]
Thanks @markvincze. I believe you :-). I've been searching and haven't found a good answer out there.
